services:
  db:
    image: mysql:8.4.4
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=cienderella
      - MYSQL_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "4306:3306"
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt